version: "3.8"

services:
  vlsm-calculator:
    image: ghcr.io/digital39999/vlsm-calculator:latest
    container_name: vlsm-calculator
    pull_policy: build
    network_mode: bridge
    restart: unless-stopped
    ports:
      - ${PORT}:3000
    environment:
      - PORT=3000
      - SESSION_SECRET=some_random_string